apiVersion: v1
kind: Secret
metadata:
  name: nats-auth-callout-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-callout.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_ACC_SIGNING_KEY: {{ .Values.jwt.accSigningKey | quote }}
  KEYCLOAK_JWK_B64: {{ .Values.keycloak.jwkB64 | quote }}
  NATS_URL: {{ .Values.nats.url | quote }}
  NATS_USER: {{ .Values.nats.user | quote }}
  NATS_PASSWORD: {{ .Values.nats.password | quote }}
