apiVersion: v1
kind: Secret
metadata:
  name: nats-bigtable-connector-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  NATS_USER: {{ .Values.nats.user | default "connector" | quote }}
  NATS_PASSWORD: {{ .Values.nats.password | required "nats.password is required" | quote }}
  NATS_HOST: {{ .Values.nats.host | default "nats.base-services.svc.cluster.local:4222" | quote }}
