{{- if .Values.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registration-server.fullname" . }}-certificates
  labels:
{{ include "registration-server.labels" . | indent 4 }}
type: Opaque
data:
  # Server identity
  server.crt.pem: {{ .Values.certificates.serverCert | b64enc }}
  server.key.pem: {{ .Values.certificates.serverKey | b64enc }}

  # Registration CA
  ca.crt.pem: {{ .Values.certificates.caCert | b64enc }}
  ca.key.pem: {{ .Values.certificates.caKey | b64enc }}

  # Trusted factory CA
  trusted-factory-ca.crt.pem: {{ .Values.certificates.factoryCaCert | b64enc }}
{{- end }}