apiVersion: v1
kind: ServiceAccount
metadata:
  name: registration-ksa
  namespace: base-services
  annotations:
    iam.gke.io/gcp-service-account: "registration-gsa@{{ .Values.gcpProjectId }}.iam.gserviceaccount.com"