apiVersion: v1
kind: Service
metadata:
  name: {{ include "registration-server.fullname" . }}
  annotations:
    {{- if eq .Values.pkiStrategy "remote" }}
    external-dns.alpha.kubernetes.io/hostname: registration.{{ .Values.baseDomain }}
    external-dns.alpha.kubernetes.io/ttl: "300"
    {{- end }}
  labels:
{{ include "registration-server.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 8080
      protocol: TCP
      name: http
    {{- if .Values.service.httpsPort }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: 8443
      protocol: TCP
      name: https
    {{- end }}
  selector:
{{ include "registration-server.selectorLabels" . | indent 4 }}
