apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . | trim }}-realm-import
  labels:
{{ include "keycloak.labels" . | indent 4 }}
data:
  sdv-telemetry-realm.json: |-
{{ .Files.Get "files/sdv-telemetry-realm.json" | indent 4 }}
