apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . | trim  }}-truststore
  labels:
{{ include "keycloak.labels" . | indent 4 }}
data:
  server-ca.pem: |-
{{ .Files.Get "files/server-ca.crt.pem" | indent 4 }}

  registration-ca.pem: |-
{{ .Files.Get "files/registration-ca.crt.pem" | indent 4 }}
